bump devDependencies, add prettier config files, update .gitignore
SFDO-Community/sticky-selectron pull request #23
Opened 2024-04-26 02:52 UTC by kalena

# Critical Changes

# Changes

Updated files similar to lwc-recipes and dreamhouse-lwc
- Bump package versions for devDependencies  
- Add package-lock.json 
- Add .prettierrc and .prettierignore 
- Update .gitignore 

# Issues Closed

2024-04-29 22:21 UTC, pickettd requested changes
Can you also remove yarn.lock in this branch/PR so that we can switch to your package-lock.json?

2024-04-29 22:21 UTC, pickettd commented on package-lock.json
@kalena since the project already has a yarn.lock - we shouldn't add a package-lock on top of that. We can switch to package-lock to match other projects that you've referenced, but in that case we should remove the yarn.lock file in this PR

2024-04-29 23:05 UTC, kalena commented on package-lock.json
@pickettd Pushed commit to remove yarn.lock
https://github.com/SFDO-Community/sticky-selectron/tree/43bab26a87a2f04365da73919da030e3f9d4316e

2024-04-30 00:33 UTC, pickettd approved these changes
Thanks Karen! Looks like we can merge

2024-04-30 00:33 UTC, merged